# -*- coding: utf-8 -*-
"""ASSIGNMENT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dkSUsnkf7THK7n7vemZ7YKlJzHnGJTJe
"""

import re

mailexp = re.compile(r'([A-Za-z0-9]+[.-_])*[A-Za-z0-9]+@[A-Za-z0-9-]+(\.[A-Z|a-z]{2,})+')
passexp = re.compile(r"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!#%*?&]{5,16}$")

def isEmailValid(email):
    if re.fullmatch(mailexp, email):
      return True
    else:
      return False
      
def isPasswordValid(password):
    if re.search(passexp,password):
        return True
    else:
        return False

def Menu():
   s='''
   Select your choice 
   1.Login
   2.Register
   3.Forgot password
   4.Exit
   '''
   print(s)
   
def EmailInstructions():
    s='''
    username should be form ()@().()
    '''
    print(s)
    
def passwordInstructions():
    s = '''
    password should consists atleast 
    one number , 
    one upper case , 
    one lower case , 
    one special character and 
    length in range of 5 - 16
    '''
    print(s)
    
    
def loaddb():
    with open('database.txt','r') as f:
        d={}
        for i in f.readlines():
            t = i.strip('\n').split(',')
            d[t[0]]=t[1]
    return d


def ValidateUserPasswordFormat():
    while True :
        password = input("Enter password : ")
        if isPasswordValid(password):
            break
        else:
            passwordInstructions()
    return password
    
    
def Register():
    
    db = loaddb()
    
    while True :
        username = input("Enter username informat of xyz@gmail.com : ")
        if isEmailValid(username):
            if username in db.keys():
                print("There already exist an account with this username please use another ")
            else:
                break
        else:
            EmailInstructions()
            
    password = ValidateUserPasswordFormat()
    
    with open('database.txt','a') as f:
        f.write('{},{}'.format(username,password)+"\n")
        
    print("User {} is succesfully Registered ".format(username))
    


def Login():
    
    db = loaddb()
    while True :
        username = input("Enter username informat of xyz@gmail.com : ")
        if isEmailValid(username):
            if username not in db.keys():
                print("User with username {} doesn't exist. Kindly Register first".format(username))
                return
            else:
                break
        else:
            EmailInstructions()
        
def Forgotpassword():
    db = loaddb()
    while True :
        username = input("Enter username informat of xyz@gmail.com : ")
        if isEmailValid(username):
            if username not in db.keys():
                print("User with username {} doesn't exist. Kindly Register first".format(username))
                return
            else:
                break
        else:
            EmailInstructions()
        
    print("User {} password is : {}".format(username,db[username]))
    return



if __name__=="__main__":
    
    Menu()
    
    while True:
        c = input("Enter your option : ")
        if c.isdigit() and int(c) in [1,2,3,4]:
            break
        else:
            print("Please select among the given choices")
        
    c=int(c)
    
    if c == 1 :
        Login()
    elif c == 2 :
        Register()
    elif c == 3:
        Forgotpassword()
    elif c == 4:
        quit()
    else:
        pass